### ISSUE TITLE
Change TubeMQ to Apache InLong

### ISSUE THREAD

**Issue by boliza** [apache/incubator-inlong-website#167]
#### Expected behavior

![image](https://user-images.githubusercontent.com/1076043/139358788-90cbcf25-8ed5-4276-b097-8ced26e02f71.png)

#### Actual behavior

Should change to Apache InLong

#### System configuration
**InLong version**: x.y

**Comment by dockerzhang** [comment]
@boliza thanks for this PR 
1, please create an issue at (the main repo)[https://github.com/apache/incubator-inlong]
2, please give the real address of the page, and we encourage that you could fix it.

**Comment by dockerzhang** [comment]
fixed by https://github.com/apache/incubator-inlong-website/pull/181
