### ISSUE TITLE
[Feature] [InLong-Agent] Modify bid and tid to inlongGroupId and inlongStreamId

### ISSUE THREAD

**Issue by EMsnap** [apache/incubator-inlong-website#170]
**Is your feature request related to a problem? Please describe.**

In the current agent module, the bid and tid (or dsid) fields are not easy to understan, so modified them to inlongGroupId and inlongStreamId.

Actual behavior
 Modify bid and tid to inlongGroupId and inlongStreamId 

Steps to reproduce
System configuration
InLong version: x.y

**Comment by dockerzhang** [comment]
duplicate with https://github.com/apache/incubator-inlong/issues/1742
