### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by bigdata-page** [apache/incubator-inlong-website#340]
#### Expected behavior
The http://localhost:3000/zh-CN/docs/next/introduction page normal

#### Actual behavior
The http://localhost:3000/zh-CN/docs/next/introduction page not found
![image](https://user-images.githubusercontent.com/8031408/162644210-d807cfd5-15ab-4cdd-8ccc-385a522318e9.png)

#### Steps to reproduce
1. start the server(command: npm start)
2. click doc/next
3. Switch the language to Chinese

#### System configuration
master

**Comment by bluewang** [comment]
Please use the command npm run start-zh
